info:
  component: Eureka - local

server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
---
spring:
  profiles: eureka1
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka2.classified.cfapps.io/eureka/

---
spring:
  profiles: eureka2
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1.classified.cfapps.io/eureka/    
